### ISSUE TITLE
Roadmap 5.x

### ISSUE THREAD

**Issue by salvoravida** [salvoravida/redux-first-history#27]
Roadmap 5.x

This issue is a roadmap for all work on the 5.x branch. 

- [x] Rewrite all with TS
- [x] Support `history` v5.x 
- [x] Support `react-router` v6.x
- [x] Deprecate/remove oldLocationChangePayload
- [x] Test coverage 100% 
- [x] Better docs

if you have any ideas... now's the time!
Let's discuss.

**Comment by salvoravida** [comment]
started branch dev-5x
- removed support for @reach/router  -> converged to react-router v6

**Comment by sirrodgepodge** [comment]
why remove @reach/router support?

**Comment by salvoravida** [comment]
@sirrodgepodge @reach/router is deprecated, the project will converch to react-router v6

https://reacttraining.com/blog/reach-react-router-future/

**Comment by salvoravida** [comment]
But maybe it could be useful to support react-routef v6 and @reach/router at the same time...

**Comment by llaenowyd** [comment]
Is react-router v6 coming soon? What's the best choice for a router lib that's available today?

**Comment by salvoravida** [comment]
> Is react-router v6 coming soon? What's the best choice for a router lib that's available today?

yesh we are waiting for out of beta v6 and for this pr merged
https://github.com/ReactTraining/react-router/pull/7586

**Comment by salvoravida** [comment]
rewritten in ts!

**Comment by salvoravida** [comment]
removed - [x] Deprecate/remove @reach/router ? (it will converge to react-router v6)

5.x will support react-router v4/v5/v6 - reach/router v1.x - history v4/v5

**Comment by salvoravida** [comment]
https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.0-beta.2

- rewritten in TS
- add support for react-router v6.0.0-beta.1

 ```tsx
import { HistoryRouter as Router } from "redux-first-history/rr6";
import { Route, Routes, Navigate } from "react-router-dom";
//...
import { store, history } from "./store";
//...

      <Router history={history}>
                  <Routes>
                    <Route path="/dashboard" element={<Dashboard />} />
                    <Route path="/" element={<Home />} />
                    <Route path="*" element={<Navigate to="/" />} />
                  </Routes>
      </Router>

 ```



demo rr6 here: https://codesandbox.io/s/redux-first-history-demo-rr6-uccuw

**Comment by mtmacdonald** [comment]
Would be nice if the docs could show a configuration example with Redux Toolkit (`configureStore`)

**Comment by salvoravida** [comment]
> Would be nice if the docs could show a configuration example with Redux Toolkit (`configureStore`)

https://codesandbox.io/s/redux-first-history-demo-forked-fy1kt?file=/src/store.js

It's quite easy:

```
import { combineReducers } from "redux";
import { configureStore } from "@reduxjs/toolkit";
import { createReduxHistoryContext, reachify } from "redux-first-history";
import { createWouterHook } from "redux-first-history/wouter";
import { createBrowserHistory } from "history";
import createSagaMiddleware from "redux-saga";
import mySaga from "./sagas";

const sagaMiddleware = createSagaMiddleware();

const {
  createReduxHistory,
  routerMiddleware,
  routerReducer
} = createReduxHistoryContext({ history: createBrowserHistory() });

export const store = configureStore({
  reducer: combineReducers({
    router: routerReducer
  }),
  middleware: [sagaMiddleware, routerMiddleware]
});

sagaMiddleware.run(mySaga);

export const history = createReduxHistory(store);
export const reachHistory = reachify(history);
export const wouterUseLocation = createWouterHook(history);

```

**Comment by mtmacdonald** [comment]
Another question: what's the best flow for accessing router "[match params](https://reactrouter.com/web/api/matchPath)" in the Redux layer?

If this package makes the store the "single source of truth" for all state (including routing state), then I would like some kind of selector which retrieves url params for direct use in the Redux layer (without having to fetch them first in React components via `useParams()`). For example, if my path is `project/1`, I want access to the project id as a store property.

My use-case is that I want to dispatch navigation actions, without the boilerplate of the React component having to look up and forward params that the store could already be aware of.

Some guidance or docs on this would be great!

**Comment by AnimaLupi** [comment]
Hello, not sure if I should open another issue or just add this here as it's related to 5.x development... hope it's the right place :-)

Anyway, React Router v6 is out and they merrily removed the history prop from `<Router>` (also from `<BrowserRouter>` and friends).
Does that rule out any possibility of integration with redux-first-history unless they re-add it? :-(

**Comment by salvoravida** [comment]
https://github.com/salvoravida/redux-first-history/releases

5.0 beta 2 already supports rr6 also the last one.

I think it's time to release rfh 5.0 final as the beta is quite stable.

Please give me a feedback if you test with rr6

**Comment by salvoravida** [comment]
> Hello, not sure if I should open another issue or just add this here as it's related to 5.x development... hope it's the right place :-)
> 
> Anyway, React Router v6 is out and they merrily removed the history prop from `<Router>` (also from `<BrowserRouter>` and friends). Does that rule out any possibility of integration with redux-first-history unless they re-add it? :-(

- rewritten in TS
- add support for react-router v6.0.0-beta.1

 ```tsx
import { HistoryRouter as Router } from "redux-first-history/rr6";
import { Route, Routes, Navigate } from "react-router-dom";
//...
import { store, history } from "./store";
//...

      <Router history={history}>
                  <Routes>
                    <Route path="/dashboard" element={<Dashboard />} />
                    <Route path="/" element={<Home />} />
                    <Route path="*" element={<Navigate to="/" />} />
                  </Routes>
      </Router>

 ```



demo rr6 here: https://codesandbox.io/s/redux-first-history-demo-rr6-uccuw

**Comment by AnimaLupi** [comment]
Thank you very much!
I was missing the new

```tsx
import { HistoryRouter as Router } from "redux-first-history/rr6";
```

With that one, things are working properly. Thanks again, looking forward for the 5.0 release! :+1:

**Comment by salvoravida** [comment]
v5.0.0 is out!
https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.0

let me know your feedback!

**Comment by salvoravida** [comment]
https://github.com/remix-run/react-router/releases/tag/v6.1.0

Finally react-router published HistoryRouter ! 🎉

**Comment by awreese** [comment]
Came here after searching what `oldLocationChangePayload` represented and what it was supposed to be used for. It appears to be deprecated but is still included in the type interface: https://github.com/salvoravida/redux-first-history/blob/328cf16b19f07a2f52138ecf6d741a9ccfec74b0/src/create.ts#L20

**Comment by salvoravida** [comment]
> Came here after searching what `oldLocationChangePayload` represented and what it was supposed to be used for. It appears to be deprecated but is still included in the type interface:
> 
> https://github.com/salvoravida/redux-first-history/blob/328cf16b19f07a2f52138ecf6d741a9ccfec74b0/src/create.ts#L20

https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.12
